before:
  hooks:
    - go mod tidy
changelog:
  skip: true
checksum:
  name_template: 'checksums.txt'
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags: -s -w
archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    replacements:
      darwin: macOS
    files:
      - src: 'commands/*'
        dst: '{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}/commands'
      - src: 'hosts.txt'
        dst: '{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}'
      - src: 'rct*'
        dst: '{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}'